# Generated by Django 6.1.1 on 2026-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('about', 'About'), ('shipping', 'Shipping'), ('returns', 'Returns'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='Rich text / HTML rendered on the footer page.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
