# Generated by Django 6.1.1 on 2026-09-25 20:17

import parcels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_reference',
            field=models.CharField(blank=True, default=parcels.models.generate_parcel_payment_reference, max_length=40),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
    ]
