# Generated by Django 6.1.1 on 2026-09-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_checkout_url_parcel_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Pay online'), ('cash', 'Cash on pickup')], default='online', max_length=20),
        ),
    ]
