# Generated by Django 6.1.1 on 2026-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_backfill_document_parcel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSizePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(choices=[('document', 'Document'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], db_index=True, help_text='The package size this rule applies to.', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label shown in the app, e.g. "Document (up to A4 sheets)".', max_length=60)),
                ('description', models.TextField(blank=True, help_text='Optional subtitle / detail text the app can show below the size name.')),
                ('icon_url', models.URLField(blank=True, help_text='Optional icon URL the Flutter app can display next to this size.')),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, help_text="If set, this exact amount is charged regardless of distance. Use for 'document' size. Leave blank for distance-based pricing.", max_digits=10, null=True)),
                ('base_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Starting fare before distance is added. Used when flat_fee is blank.', max_digits=10, null=True)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost per kilometre. Used when flat_fee is blank.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are hidden from the Flutter app and ignored by the pricing engine.')),
            ],
            options={
                'verbose_name': 'Package size pricing',
                'verbose_name_plural': 'Package size pricing',
                'ordering': ['size', '-updated_at'],
            },
        ),
    ]
