# Generated by Django 6.1.1 on 2026-09-21 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('flag_type', models.CharField(choices=[('coupon_abuse', 'Coupon abuse'), ('review_farming', 'Review farming'), ('multiple_accounts', 'Multiple accounts'), ('payment_anomaly', 'Payment anomaly')], max_length=30)),
                ('score', models.DecimalField(decimal_places=2, help_text='Higher = more suspicious.', max_digits=5)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=30)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='risk_riskfl_content_9b7726_idx')],
            },
        ),
    ]
