# Generated by Django 6.1.1 on 2026-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='business_certificate',
            field=models.FileField(blank=True, help_text='Business registration certificate, if the business is formally registered.', upload_to='seller_applications/certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='id_document',
            field=models.FileField(blank=True, help_text='Government-issued ID (e.g. national ID, passport) - required before review.', upload_to='seller_applications/ids/%Y/%m/'),
        ),
    ]
