# Generated by Django 6.1.1 on 2026-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_sellerapplication_business_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payout',
            name='account_details',
            field=models.CharField(blank=True, help_text='Destination account/number for this payout, e.g. mobile money number.', max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='admin_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_date',
            field=models.DateField(blank=True, help_text='Set once the payout is scheduled or paid.', null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
