# Generated by Django 6.1.1 on 2026-09-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seller_min_free_delivery_threshold'),
        ('sellers', '0005_subscriptionplan_sellersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='momo_network',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='momo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='sellers/bulk_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list, help_text='List of {row, errors} entries for rows that failed validation.')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_jobs', to='catalog.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bank', 'Bank account'), ('momo', 'Mobile money')], max_length=20)),
                ('account_reference', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='catalog.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
