# Generated by Django 6.1.1 on 2026-09-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_delivery_size'),
        ('deliveries', '0004_delivery_initiated_by_delivery_request_mode_and_more'),
        ('riders', '0003_remove_riderearning_amount_riderearning_base_fare_and_more'),
        ('sellers', '0006_sellerapplication_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerFavoriteRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='riders.riderprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_riders', to='catalog.seller')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('seller', 'rider'), name='unique_seller_favorite_rider')],
            },
        ),
        migrations.CreateModel(
            name='SellerFulfillmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_ratings_given', to='riders.riderprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_ratings', to='catalog.seller')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_fulfillment_rating', to='deliveries.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='seller_fulfillment_rating_stars_1_to_5')],
            },
        ),
        migrations.CreateModel(
            name='SellerRiderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='riders.riderprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_riders', to='catalog.seller')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('seller', 'rider'), name='unique_seller_rider_block')],
            },
        ),
    ]
