# Generated by Django 6.1.1 on 2026-09-12 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', through='accounts.UserInterest', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['destination', 'purpose', 'is_used'], name='accounts_ot_destina_ed57bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'category')},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='user_must_have_email_or_phone'),
        ),
    ]
