# Generated by Django 6.1.1 on 2026-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
