# Generated by Django 6.1.1 on 2026-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('label', models.CharField(help_text="e.g. 'General support', 'Sales', 'WhatsApp'", max_length=100)),
                ('value', models.CharField(help_text='The email address or phone number itself.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
