# Generated by Django 6.1.1 on 2026-09-22 00:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Flips to True automatically once every required document is verified.')),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('min_trip_value', models.DecimalField(blank=True, decimal_places=2, help_text='Only offer this rider trips worth at least this much. Blank = no minimum.', max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bank', 'Bank account'), ('momo', 'Mobile money')], max_length=20)),
                ('account_reference', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van')], max_length=20)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='riders/vehicles/')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('government_id', 'Government ID'), ('drivers_licence', "Driver's licence"), ('vehicle_registration', 'Vehicle registration'), ('profile_photo', 'Profile photo')], max_length=30)),
                ('file', models.FileField(upload_to='riders/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('expires_at', models.DateField(blank=True, help_text='For licences/registrations that expire.', null=True)),
                ('reviewer_note', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('rider', 'doc_type'), name='unique_rider_document_per_type')],
            },
        ),
    ]
