# Generated by Django 6.1.1 on 2026-09-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_proofofdelivery'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='riders.riderprofile')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='deliveries.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
