# Generated by Django 6.1.1 on 2026-09-25 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_remove_riderearning_amount_riderearning_base_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderpayoutaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderpayoutaccount',
            name='masked_number',
            field=models.CharField(blank=True, help_text="Display-only, e.g. '•••• 1122' - never the full account/MoMo number.", max_length=30),
        ),
        migrations.AddField(
            model_name='riderpayoutaccount',
            name='provider',
            field=models.CharField(blank=True, help_text="e.g. 'MTN Mobile Money', 'GCB Bank'.", max_length=100),
        ),
        migrations.CreateModel(
            name='RiderOnlineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
