# Generated by Django 6.1.1 on 2026-09-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rating_range',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
