# Generated by Django 6.1.1 on 2026-09-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_banner_image_url_brand_logo_url_category_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='seller',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
