# Generated by Django 6.1.1 on 2026-09-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seller_primary_category_seller_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Scanned at the point of sale; falls back to SKU when blank.', max_length=64, null=True, unique=True),
        ),
    ]
