# Generated by Django 6.1.1 on 2026-09-13 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted-average unit cost, updated when purchase orders are received. Used for COGS/profit reporting.', max_digits=10),
        ),
    ]
