# Generated by Django 6.1.1 on 2026-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True, help_text='Whether a customer can request a return for this product after delivery.'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after delivery a return can still be requested.'),
        ),
    ]
