# Generated by Django 6.1.1 on 2026-09-15 10:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_returnable_product_return_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission percentage on sales in this category (e.g. 10.00 for 10%).', max_digits=5),
        ),
    ]
