# Generated by Django 6.1.1 on 2026-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='min_free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cart subtotal (for this seller's items) above which delivery is free. Leave blank to use the platform default.", max_digits=10, null=True),
        ),
    ]
