# Generated by Django 6.1.1 on 2026-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seller_min_free_delivery_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Used to filter which rider vehicle types can carry this item. Blank = no requirement.', max_length=20),
        ),
    ]
