# Generated by Django 6.1.1 on 2026-09-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_seller_pickup_lat_seller_pickup_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='has_warehouse',
            field=models.BooleanField(default=False, help_text="Whether this seller keeps backroom/overstock inventory in a warehouse, separate from what's listed as available on the storefront (Product.stock_qty). Enables warehouse stock tracking and importing units into a product's sellable stock when it runs out."),
        ),
    ]
