# Generated by Django 6.1.1 on 2026-09-21 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0009_seller_min_free_delivery_threshold'),
        ('orders', '0009_delete_dispute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='coupons/banners/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Shown on the public Deals & Promotions page.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max redemptions per user. Leave blank for no per-user cap.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('platform', 'Platform-wide'), ('seller', 'Seller')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(blank=True, help_text="Required for scope=seller - the discount only applies to this seller's items in the cart.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='catalog.seller'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="For a seller coupon, checked against that seller's subtotal alone, not the whole cart.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max total redemptions across all users.', null=True),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='cart.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
