# Generated by Django 6.1.1 on 2026-09-21 09:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_seller_order_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('not_as_described', 'Not as described'), ('damaged', 'Damaged'), ('wrong_item', 'Wrong item'), ('changed_mind', 'Changed mind'), ('other', 'Other')], max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of uploaded photo URLs.')),
                ('refund_type', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange')], default='refund', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.orderitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('refund_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.refundrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_status_changes', to=settings.AUTH_USER_MODEL)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.refundrequest')),
            ],
            options={
                'verbose_name_plural': 'refund status histories',
                'ordering': ['created_at'],
            },
        ),
    ]
