# Generated by Django 6.1.1 on 2026-09-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refundrequest_dispute_refundstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispute',
        ),
    ]
