# Generated by Django 6.1.1 on 2026-09-22 08:14

import deliveries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(default=deliveries.models.generate_delivery_otp, max_length=4)),
                ('otp_verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deliveries/proof/%Y/%m/')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='deliveries.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
