# Generated by Django 6.1.1 on 2026-09-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_rider_base_fare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='initiated_by',
            field=models.CharField(choices=[('system', 'System'), ('seller', 'Seller')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='request_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('direct', 'Direct')], default='auto', help_text="'direct' offers never cascade to nearest-match on expiry/decline - see cancel_delivery/expire_offer.", max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='The seller who manually requested a rider, if any - blank for system-triggered dispatch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
