from django.urls import path

from . import console_views, invoice_views, pos_views, seller_application_views, store_ops_views, views

urlpatterns = [
    path("", views.home, name="web-home"),
    path("login/", views.login_view, name="web-login"),
    path("logout/", views.logout_view, name="web-logout"),
    path("register/", views.register_view, name="web-register"),
    path("verify/", views.verify_view, name="web-verify"),
    path("forgot-password/", views.forgot_password_view, name="web-forgot-password"),
    path("reset-password/<uidb64>/<token>/", views.reset_password_view, name="web-reset-password"),
    path("password-updated/", views.password_updated_view, name="web-password-updated"),
    path("auth/social/<provider>/", views.social_login_view, name="web-social-login"),

    path("search/", views.search_view, name="web-search"),
    path("categories/", views.category_list_view, name="web-category-list"),
    path("categories/<slug:slug>/", views.category_detail_view, name="web-category-detail"),
    path("brands/<slug:slug>/", views.brand_detail_view, name="web-brand-detail"),
    path("collections/<slug:slug>/", views.collection_detail_view, name="web-collection-detail"),
    path("deals/", views.deals_view, name="web-deals"),
    path("new-arrivals/", views.new_arrivals_view, name="web-new-arrivals"),
    path("products/<slug:slug>/", views.product_detail_view, name="web-product-detail"),
    path("products/<slug:slug>/reviews/add/", views.product_review_add_view, name="web-product-review-add"),
    path("sellers/<slug:slug>/", views.seller_detail_view, name="web-seller-detail"),

    path("wishlist/", views.wishlist_view, name="web-wishlist"),
    path("wishlist/toggle/", views.wishlist_toggle_view, name="web-wishlist-toggle"),
    path("wishlist/<int:product_id>/move-to-cart/", views.wishlist_move_to_cart_view, name="web-wishlist-move-to-cart"),
    path("cart/", views.cart_view, name="web-cart"),
    path("cart/add/", views.cart_add_view, name="web-cart-add"),
    path("cart/items/<int:item_id>/update/", views.cart_item_update_view, name="web-cart-item-update"),
    path("cart/items/<int:item_id>/remove/", views.cart_item_remove_view, name="web-cart-item-remove"),
    path("cart/coupon/", views.cart_coupon_apply_view, name="web-cart-coupon-apply"),
    path("checkout/", views.checkout_view, name="web-checkout"),
    path("checkout/hubtel/return/", views.hubtel_return_view, name="web-hubtel-return"),
    path("addresses/add/", views.address_add_view, name="web-address-add"),
    path("orders/<str:order_number>/confirmation/", views.order_confirmation_view, name="web-order-confirmation"),
    path("orders/<str:order_number>/request-return/", views.order_request_return_view, name="web-order-request-return"),

    path("become-seller/", seller_application_views.become_seller_view, name="web-become-seller"),

    path("notifications/", views.notifications_view, name="web-notifications"),
    path("support/", views.support_view, name="web-support"),
    path("pages/<slug:slug>/", views.static_page_view, name="static-page"),

    path("account/", views.account_overview_view, name="web-account-overview"),
    path("account/edit/", views.account_edit_view, name="web-account-edit"),
    path("account/preferences/toggle/", views.account_preference_toggle_view, name="web-account-preference-toggle"),
    path("account/orders/", views.account_orders_view, name="web-account-orders"),
    path("account/addresses/", views.account_addresses_view, name="web-account-addresses"),
    path("account/addresses/<int:address_id>/edit/", views.address_edit_view, name="web-address-edit"),
    path("account/addresses/<int:address_id>/delete/", views.address_delete_view, name="web-address-delete"),
    path("account/addresses/<int:address_id>/set-default/", views.address_set_default_view, name="web-address-set-default"),
    path("account/payment-methods/", views.account_payment_methods_view, name="web-account-payment-methods"),
    path("account/payment-methods/add/", views.payment_method_add_view, name="web-payment-method-add"),
    path("account/payment-methods/<int:token_id>/delete/", views.payment_method_delete_view, name="web-payment-method-delete"),
    path("account/payment-methods/<int:token_id>/set-default/", views.payment_method_set_default_view, name="web-payment-method-set-default"),

    path("seller/", views.seller_overview_view, name="web-seller-overview"),
    path("seller/products/", views.seller_products_view, name="web-seller-products"),
    path("seller/products/add/", views.seller_product_add_view, name="web-seller-product-add"),
    path("seller/products/<int:product_id>/edit/", views.seller_product_edit_view, name="web-seller-product-edit"),
    path("seller/products/<int:product_id>/toggle/", views.seller_product_toggle_view, name="web-seller-product-toggle"),
    path("seller/products/<int:product_id>/delete/", views.seller_product_delete_view, name="web-seller-product-delete"),
    path("seller/products/<int:product_id>/variants/add/", views.seller_product_variant_add_view, name="web-seller-product-variant-add"),
    path("seller/products/<int:product_id>/variants/<int:variant_id>/delete/", views.seller_product_variant_delete_view, name="web-seller-product-variant-delete"),
    path("seller/products/<int:product_id>/images/<int:image_id>/delete/", views.seller_product_image_delete_view, name="web-seller-product-image-delete"),
    path("seller/orders/", views.seller_orders_view, name="web-seller-orders"),
    path("seller/orders/<str:order_number>/status/", views.seller_order_status_update_view, name="web-seller-order-status"),
    path("seller/order-returns/", views.seller_order_returns_view, name="web-seller-order-returns"),
    path("seller/order-returns/<int:return_id>/resolve/", views.seller_order_return_resolve_view, name="web-seller-order-return-resolve"),
    path("seller/flash-deals/", views.seller_flash_deals_view, name="web-seller-flash-deals"),
    path("seller/flash-deals/add/", views.seller_flash_deal_add_view, name="web-seller-flash-deal-add"),
    path("seller/flash-deals/<int:flash_deal_id>/edit/", views.seller_flash_deal_edit_view, name="web-seller-flash-deal-edit"),
    path("seller/flash-deals/<int:flash_deal_id>/toggle/", views.seller_flash_deal_toggle_view, name="web-seller-flash-deal-toggle"),
    path("seller/flash-deals/<int:flash_deal_id>/delete/", views.seller_flash_deal_delete_view, name="web-seller-flash-deal-delete"),
    path("seller/export/", views.seller_export_report_view, name="web-seller-export"),
    path("seller/payouts/", views.seller_payouts_view, name="web-seller-payouts"),
    path("seller/payouts/request/", views.seller_payout_request_view, name="web-seller-payout-request"),
    path("seller/settings/", views.seller_settings_view, name="web-seller-settings"),
    path("seller/subscription/", views.seller_subscription_view, name="web-seller-subscription"),
    path("seller/subscription/checkout/", views.seller_subscription_checkout_view, name="web-seller-subscription-checkout"),
    path("seller/subscription/return/", views.seller_subscription_return_view, name="web-seller-subscription-return"),

    path("seller/employees/", pos_views.seller_employees_view, name="web-seller-employees"),
    path("seller/employees/add/", pos_views.seller_employee_add_view, name="web-seller-employee-add"),
    path("seller/employees/<int:employee_id>/edit/", pos_views.seller_employee_edit_view, name="web-seller-employee-edit"),
    path("seller/employees/<int:employee_id>/toggle/", pos_views.seller_employee_toggle_view, name="web-seller-employee-toggle"),
    path("seller/employees/<int:employee_id>/delete/", pos_views.seller_employee_delete_view, name="web-seller-employee-delete"),

    path("seller/pos/", pos_views.pos_terminal_view, name="web-pos-terminal"),
    path("seller/pos/clock-in/", pos_views.pos_clock_in_view, name="web-pos-clock-in"),
    path("seller/pos/clock-out/", pos_views.pos_clock_out_view, name="web-pos-clock-out"),
    path("seller/pos/lookup/", pos_views.pos_lookup_view, name="web-pos-lookup"),
    path("seller/pos/checkout/", pos_views.pos_checkout_view, name="web-pos-checkout"),
    path("seller/pos/receipt/<str:receipt_number>/", pos_views.pos_receipt_view, name="web-pos-receipt"),
    path("seller/pos/sales/", pos_views.pos_sales_history_view, name="web-pos-sales"),
    path("seller/pos/reports/", pos_views.pos_reports_view, name="web-pos-reports"),

    path("seller/suppliers/", store_ops_views.seller_suppliers_view, name="web-seller-suppliers"),
    path("seller/suppliers/add/", store_ops_views.seller_supplier_add_view, name="web-seller-supplier-add"),
    path("seller/suppliers/<int:supplier_id>/toggle/", store_ops_views.seller_supplier_toggle_view, name="web-seller-supplier-toggle"),

    path("seller/purchase-orders/", store_ops_views.seller_purchase_orders_view, name="web-seller-purchase-orders"),
    path("seller/purchase-orders/add/", store_ops_views.seller_purchase_order_add_view, name="web-seller-purchase-order-add"),
    path("seller/purchase-orders/<int:po_id>/receive/", store_ops_views.seller_purchase_order_receive_view, name="web-seller-purchase-order-receive"),
    path("seller/purchase-orders/<int:po_id>/cancel/", store_ops_views.seller_purchase_order_cancel_view, name="web-seller-purchase-order-cancel"),

    path("seller/inventory/", store_ops_views.seller_inventory_view, name="web-seller-inventory"),
    path("seller/inventory/export/", store_ops_views.seller_inventory_export_view, name="web-seller-inventory-export"),
    path("seller/inventory/batches/<int:batch_id>/write-off/", store_ops_views.seller_batch_write_off_view, name="web-seller-batch-write-off"),

    path("seller/expenses/", store_ops_views.seller_expenses_view, name="web-seller-expenses"),
    path("seller/expenses/add/", store_ops_views.seller_expense_add_view, name="web-seller-expense-add"),

    path("seller/payroll/", store_ops_views.seller_payroll_view, name="web-seller-payroll"),
    path("seller/payroll/run/", store_ops_views.seller_payroll_run_view, name="web-seller-payroll-run"),
    path("seller/payroll/export/", store_ops_views.seller_payroll_export_view, name="web-seller-payroll-export"),
    path("seller/payroll/<int:pay_run_id>/", store_ops_views.seller_payroll_detail_view, name="web-seller-payroll-detail"),
    path("seller/payroll/<int:pay_run_id>/mark-paid/", store_ops_views.seller_payroll_mark_paid_view, name="web-seller-payroll-mark-paid"),
    path("seller/payroll/payslips/<int:payslip_id>/update/", store_ops_views.seller_payslip_update_view, name="web-seller-payslip-update"),

    path("seller/discounts/", store_ops_views.seller_discounts_view, name="web-seller-discounts"),
    path("seller/discounts/add/", store_ops_views.seller_discount_add_view, name="web-seller-discount-add"),
    path("seller/discounts/export/", store_ops_views.seller_discounts_export_view, name="web-seller-discounts-export"),
    path("seller/discounts/<int:discount_id>/toggle/", store_ops_views.seller_discount_toggle_view, name="web-seller-discount-toggle"),
    path("seller/discounts/<int:discount_id>/delete/", store_ops_views.seller_discount_delete_view, name="web-seller-discount-delete"),

    path("seller/customers/", store_ops_views.seller_customers_view, name="web-seller-customers"),
    path("seller/customers/add/", store_ops_views.seller_customer_add_view, name="web-seller-customer-add"),
    path("seller/customers/export/", store_ops_views.seller_customers_export_view, name="web-seller-customers-export"),
    path("seller/customers/<int:customer_id>/", store_ops_views.seller_customer_detail_view, name="web-seller-customer-detail"),

    path("seller/pos/returns/", store_ops_views.seller_returns_view, name="web-seller-returns"),
    path("seller/pos/returns/process/", store_ops_views.seller_return_process_view, name="web-seller-return-process"),

    path("seller/reports/", store_ops_views.seller_reports_hub_view, name="web-seller-reports"),
    path("seller/reports/pnl/", store_ops_views.seller_pnl_view, name="web-seller-pnl"),
    path("seller/reports/pnl/export/", store_ops_views.seller_pnl_export_view, name="web-seller-pnl-export"),
    path("seller/reports/suppliers/export/", store_ops_views.seller_suppliers_export_view, name="web-seller-suppliers-export"),

    path("seller/invoices/", invoice_views.seller_invoices_view, name="web-seller-invoices"),
    path("seller/invoices/add/", invoice_views.seller_invoice_add_view, name="web-seller-invoice-add"),
    path("seller/invoices/export/", invoice_views.seller_invoices_export_view, name="web-seller-invoices-export"),
    path("seller/invoices/<int:invoice_id>/", invoice_views.seller_invoice_detail_view, name="web-seller-invoice-detail"),
    path("seller/invoices/<int:invoice_id>/payments/add/", invoice_views.seller_invoice_payment_add_view, name="web-seller-invoice-payment-add"),
    path("seller/invoices/<int:invoice_id>/send/", invoice_views.seller_invoice_send_view, name="web-seller-invoice-send"),
    path("seller/invoices/<int:invoice_id>/void/", invoice_views.seller_invoice_void_view, name="web-seller-invoice-void"),

    path("console/", console_views.console_overview_view, name="web-console-overview"),
    path("console/export/", console_views.console_overview_export_view, name="web-console-overview-export"),
    path("console/seller-applications/", console_views.console_seller_applications_view, name="web-console-seller-applications"),
    path("console/seller-applications/export/", console_views.console_seller_applications_export_view, name="web-console-seller-applications-export"),
    path("console/seller-applications/<int:application_id>/approve/", console_views.console_seller_application_approve_view, name="web-console-seller-application-approve"),
    path("console/seller-applications/<int:application_id>/reject/", console_views.console_seller_application_reject_view, name="web-console-seller-application-reject"),
    path("console/orders/", console_views.console_orders_view, name="web-console-orders"),
    path("console/orders/export/", console_views.console_orders_export_view, name="web-console-orders-export"),
    path("console/users/", console_views.console_users_view, name="web-console-users"),
    path("console/users/add/", console_views.console_user_add_view, name="web-console-user-add"),
    path("console/users/export/", console_views.console_users_export_view, name="web-console-users-export"),
    path("console/users/<int:user_id>/toggle-active/", console_views.console_user_toggle_active_view, name="web-console-user-toggle-active"),
    path("console/products/", console_views.console_products_view, name="web-console-products"),
    path("console/products/export/", console_views.console_products_export_view, name="web-console-products-export"),
    path("console/products/<int:product_id>/toggle/", console_views.console_product_toggle_view, name="web-console-product-toggle"),
    path("console/payouts/", console_views.console_payouts_view, name="web-console-payouts"),
    path("console/payouts/export/", console_views.console_payouts_export_view, name="web-console-payouts-export"),
    path("console/payouts/<int:payout_id>/schedule/", console_views.console_payout_schedule_view, name="web-console-payout-schedule"),
    path("console/payouts/<int:payout_id>/mark-paid/", console_views.console_payout_mark_paid_view, name="web-console-payout-mark-paid"),
    path("console/payouts/<int:payout_id>/reject/", console_views.console_payout_reject_view, name="web-console-payout-reject"),
    path("console/categories/", console_views.console_categories_view, name="web-console-categories"),
    path("console/categories/add/", console_views.console_category_add_view, name="web-console-category-add"),
    path("console/categories/<int:category_id>/edit/", console_views.console_category_edit_view, name="web-console-category-edit"),
    path("console/categories/<int:category_id>/toggle/", console_views.console_category_toggle_view, name="web-console-category-toggle"),
    path("console/categories/<int:category_id>/delete/", console_views.console_category_delete_view, name="web-console-category-delete"),
    path("console/categories/<int:category_id>/subcategories/add/", console_views.console_subcategory_add_view, name="web-console-subcategory-add"),
    path("console/categories/<int:category_id>/subcategories/<int:subcategory_id>/toggle/", console_views.console_subcategory_toggle_view, name="web-console-subcategory-toggle"),
    path("console/categories/<int:category_id>/subcategories/<int:subcategory_id>/delete/", console_views.console_subcategory_delete_view, name="web-console-subcategory-delete"),
    path("console/delivery-methods/", console_views.console_delivery_methods_view, name="web-console-delivery-methods"),
    path("console/delivery-methods/add/", console_views.console_delivery_method_add_view, name="web-console-delivery-method-add"),
    path("console/delivery-methods/<int:delivery_method_id>/edit/", console_views.console_delivery_method_edit_view, name="web-console-delivery-method-edit"),
    path("console/delivery-methods/<int:delivery_method_id>/toggle/", console_views.console_delivery_method_toggle_view, name="web-console-delivery-method-toggle"),
    path("console/delivery-methods/<int:delivery_method_id>/delete/", console_views.console_delivery_method_delete_view, name="web-console-delivery-method-delete"),
    path("console/brands/", console_views.console_brands_view, name="web-console-brands"),
    path("console/brands/add/", console_views.console_brand_add_view, name="web-console-brand-add"),
    path("console/brands/<int:brand_id>/edit/", console_views.console_brand_edit_view, name="web-console-brand-edit"),
    path("console/brands/<int:brand_id>/toggle/", console_views.console_brand_toggle_view, name="web-console-brand-toggle"),
    path("console/brands/<int:brand_id>/delete/", console_views.console_brand_delete_view, name="web-console-brand-delete"),
    path("console/banners/", console_views.console_banners_view, name="web-console-banners"),
    path("console/banners/add/", console_views.console_banner_add_view, name="web-console-banner-add"),
    path("console/banners/<int:banner_id>/edit/", console_views.console_banner_edit_view, name="web-console-banner-edit"),
    path("console/banners/<int:banner_id>/toggle/", console_views.console_banner_toggle_view, name="web-console-banner-toggle"),
    path("console/banners/<int:banner_id>/delete/", console_views.console_banner_delete_view, name="web-console-banner-delete"),
    path("console/collections/", console_views.console_collections_view, name="web-console-collections"),
    path("console/collections/add/", console_views.console_collection_add_view, name="web-console-collection-add"),
    path("console/collections/<int:collection_id>/edit/", console_views.console_collection_edit_view, name="web-console-collection-edit"),
    path("console/collections/<int:collection_id>/toggle/", console_views.console_collection_toggle_view, name="web-console-collection-toggle"),
    path("console/collections/<int:collection_id>/delete/", console_views.console_collection_delete_view, name="web-console-collection-delete"),
]
